task_name: video_enhancement
task_type: image
input_file: "/data/LLVT/MIMO-UNet/data/GOPRO_Large/test/GOPR0384_11_00/blur/"
output_file: "/cache"
windows_size: 1
fixed_width: 0
fixed_height: 0
up_scale: 1
color_space: rgb
tasks:
  - task_name: image deblur
    task_type: super_resolution
    data_io: basic
    backend: ascend
    dtype: float16
    model_file: null
    once_process_frames: 1
    frame_overlap: 0
    patch_overlap: 0
    up_scale: 1
    tiling: "default"
