system:
  random_seed: 1
  mindspore_seed: 1
  numpy_seed: 1
  context_mode: "graph_mode"
  graph_kernel_flags: null


dataset:
  dataset_name: "mai21denoise"
  input_path: "/data/LLVT/NoahTCV/data/mai21denoise_crops/"
  batch_size: 64
  num_parallel_workers: 8
  num_frames: 0
  scale: 1
  dataset_sink_mode: True


val_dataset:
  dataset_name: "cbsd68"
  input_path: "/data/LLVT/NoahTCV/data/CBSD68"
  eval_batch_size: 1
  num_frames: 0
  scale: 1
  noise_level: 50

  dataset_sink_mode: False
  num_parallel_workers: 8


model:
  name: "noahtcv"
  load_path: "/data/LLVT/NoahTCV/ckpt/best_gpu.ckpt"

loss:
  name: "MSELoss"
  loss_scale: 1.0
  amp_level: "O0"

scheduler:
  base_lr: 1.0e-4
  min_lr: 1.0e-5

  name: "cosine_annealing"

  weight_decay: 0
  warmup_epochs: 0
  warmup_factor: 1.0

# Optimizer options
optimizer:
  name: "Adam"
  learning_rate: 1.0e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999


metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null

train_params:
  epoch_size: 200
  need_val: True
  keep_checkpoint_max: 60
  save_epoch_frq: 10
  eval_frequency: 50
  print_frequency: 10
  ckpt_save_dir: "./ckpt/noahtcv"

train_pipeline: null
test_pipeline: null
