task_name: video_enhancement
task_type: image
input_file: "/data/LLVT/BasicVSR_plus_plus/data/Set8/motorbike"
output_file: "/cache/rrdb_task_srx4"
windows_size: 1
fixed_width: 0
fixed_height: 0
up_scale: 4
color_space: rgb
tasks:
  - task_name: image vsr
    task_type: super_resolution
    data_io: basic
    backend: ascend
    dtype: float16
    model_file: "/data/LLVT/ACL/om/rrdb_512_512.om"
    once_process_frames: 1
    frame_overlap: 0
    patch_overlap: 0
    up_scale: 4
    tiling: "default"
